--- #YAML:1.0
name: Parse-CPAN-Packages
version: 2.26
author:
  - Leon Brocard <acme@astray.com>
abstract: Parse 02packages.details.txt.gz
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
