--- #YAML:1.0
name: Parse-CPAN-Packages
version: 2.19
author:
  - Leon Brocard <acme@astray.com>
abstract: Parse 02packages.details.txt.gz
license: perl
requires:
  CPAN::DistnameInfo: 0
  Class::Accessor::Chained: 0
  Test::More: 0
provides:
  Parse::CPAN::Packages:
    file: lib/Parse/CPAN/Packages.pm
    version: 2.19
  Parse::CPAN::Packages::Distribution:
    file: lib/Parse/CPAN/Packages/Distribution.pm
    version: 2.12
  Parse::CPAN::Packages::Package:
    file: lib/Parse/CPAN/Packages/Package.pm
    version: 2.12
generated_by: Module::Build version 0.24
